name: Deploy HyP3
description: Deploy a HyP3 stack

inputs:
  TEMPLATE_BUCKET:
    description: "S3 Bucket for CloudFormation deployment artifacts"
    required: true
  STACK_NAME:
    description: "Name of the deployed stack"
    required: true
  DOMAIN_NAME:
    description: "HyP3 API domain name"
    required: true
  CERTIFICATE_ARN:
    description: "ARN for AWS Certificate Manager SSL certificate"
    required: true
  IMAGE_TAG:
    description: "HyP3 plugin docker image tag to pull"
    required: true
  PRODUCT_LIFETIME:
    description: "Number of days to keep output files before deleting them"
    required: true
  VPC_ID:
    description: "Default VPC ID"
    required: true
  SUBNET_IDS:
    description: "Comma separated list of Subnet IDs"
    required: true
  EDL_USERNAME:
    description: "EarthData Login name to use when downloading data from ASF"
    required: true
  EDL_PASSWORD:
    description: "EarthData Login password to use when downloading data from ASF"
    required: true
  CLOUDFORMATION_ROLE_ARN:
    description: "The CloudFormation role to use for this deployment"
    required: true
  MONTHLY_JOB_QUOTA_PER_USER:
    description: "The default number of jobs any user with an Earthdata Login can run per month"
    required: true
  JOB_FILES:
    description: "Space seperated list of job spec YAMLs to include"
    required: true
  BANNED_CIDR_BLOCKS:
    description: "Comma separated list of IP CIDR blocks that will receive HTTP 403 FORBIDDEN responses from the API"
    required: true
  MONTHLY_COMPUTE_BUDGET:
    description: "Total budget allocated for AWS Batch processing per month, in dollars. Ignored when DefaultMaxvCpus = ExpandedMaxvCpus."
    required: true
  DEFAULT_MAX_VCPUS:
    description: "Default maximum size for the AWS Batch compute environment"
    required: true
  EXPANDED_MAX_VCPUS:
    description: "Expanded maximum size for the AWS Batch compute environment to use when month-to-date budget sufficiently exceeds month-to-date spending"
    required: true
  REQUIRED_SURPLUS:
    description: "Amount by which month-to-date budget must exceed month-to-date spending to increase fleet size, in dollars. Ignored when DefaultMaxvCpus = ExpandedMaxvCpus."
    required: true

runs:
  using: "composite"
  steps:
      - name: install dependancies and render templates
        shell: bash
        run: |
          pip install --upgrade pip
          make install
          make files='${{ inputs.JOB_FILES }}' render
          python -m pip install -r requirements-apps-api.txt -t apps/api/src
          python -m pip install -r requirements-apps-process-new-granules.txt -t apps/process-new-granules/src
          python -m pip install -r requirements-apps-update-db.txt -t apps/update-db/src
          python -m pip install -r requirements-apps-scale-cluster.txt -t apps/scale-cluster/src
          python -m pip install -r requirements-apps-start-execution.txt -t apps/start-execution/src
      - name: Package and deploy
        shell: bash
        run: |
          aws cloudformation package \
            --template-file apps/main-cf.yml \
            --s3-bucket ${{ inputs.TEMPLATE_BUCKET }} \
            --output-template-file packaged.yml
          aws cloudformation deploy \
            --stack-name ${{ inputs.STACK_NAME }} \
            --template-file packaged.yml \
            --role-arn ${{ inputs.CLOUDFORMATION_ROLE_ARN }} \
            --capabilities CAPABILITY_IAM \
            --parameter-overrides \
                VpcId='${{ inputs.VPC_ID }}' \
                SubnetIds='${{ inputs.SUBNET_IDS }}' \
                EDLUsername='${{ inputs.EDL_USERNAME }}' \
                EDLPassword='${{ inputs.EDL_PASSWORD }}' \
                ImageTag='${{ inputs.IMAGE_TAG }}' \
                ProductLifetimeInDays='${{ inputs.PRODUCT_LIFETIME }}' \
                DomainName='${{ inputs.DOMAIN_NAME }}' \
                CertificateArn='${{ inputs.CERTIFICATE_ARN }}' \
                MonthlyJobQuotaPerUser='${{ inputs.MONTHLY_JOB_QUOTA_PER_USER }}' \
                BannedCidrBlocks='${{ inputs.BANNED_CIDR_BLOCKS }}' \
                MonthlyComputeBudget='${{ inputs.MONTHLY_COMPUTE_BUDGET }}' \
                DefaultMaxvCpus='${{ inputs.DEFAULT_MAX_VCPUS }}' \
                ExpandedMaxvCpus='${{ inputs.EXPANDED_MAX_VCPUS }}' \
                RequiredSurplus='${{ inputs.REQUIRED_SURPLUS }}'
