name: Deploy HyP3
description: Deploy a HyP3 stack

inputs:
  TEMPLATE_BUCKET:
    description: "S3 Bucket for CloudFormation deployment artifacts"
    required: true
  STACK_NAME:
    description: "Name of the deployed stack"
    required: true
  API_NAME:
    description: "HyP3 API name"
    required: true
  CLOUDFORMATION_ROLE_ARN:
    description: "The CloudFormation role to use for this deployment"
    required: true
  COST_PROFILE:
    description: "Job spec cost profile"
    required: true
  JOB_FILES:
    description: "Space separated list of job spec YAMLs to include"
    required: true
  SECURITY_ENVIRONMENT:
    description: "Modify resources/configurations for ASF (default), EDC, or JPL security environments"
    required: true
  PARAMETER_FILE:
    description: "JSON file containing parameter overrides for cloudformation stack"
    required: true

runs:
  using: "composite"
  steps:
      - name: install dependencies and render templates
        shell: bash
        run: |
          pip install --upgrade pip
          make install
          make files='${{ inputs.JOB_FILES }}' security_environment='${{ inputs.SECURITY_ENVIRONMENT }}' api_name='${{ inputs.API_NAME }}' cost_profile='${{ inputs.COST_PROFILE }}' build
      - name: Package and deploy
        shell: bash
        run: |
          [ -z ${{ inputs.CLOUDFORMATION_ROLE_ARN }} ] && export ROLE_STATEMENT="" \
            || export ROLE_STATEMENT="--role-arn ${{ inputs.CLOUDFORMATION_ROLE_ARN }}"

          aws cloudformation package \
            --template-file apps/main-cf.yml \
            --s3-bucket ${{ inputs.TEMPLATE_BUCKET }} \
            --output-template-file packaged.yml
          aws cloudformation deploy \
            --stack-name ${{ inputs.STACK_NAME }} \
            --template-file packaged.yml \
            $ROLE_STATEMENT \
            --capabilities CAPABILITY_IAM \
            --parameter-overrides file://${{ inputs.PARAMETER_FILE }}
