name: Deploy HyP3
description: Deploy a HyP3 stack

inputs:
  TEMPLATE_BUCKET:
    description: "S3 Bucket for CloudFormation deployment artifacts"
    required: true
  STACK_NAME:
    description: "Name of the deployed stack"
    required: true
  DOMAIN_NAME:
    description: "HyP3 API domain name"
    required: true
  CERTIFICATE_ARN:
    description: "ARN for AWS Certificate Manager SSL certificate"
    required: true
  IMAGE_TAG:
    description: "HyP3 plugin docker image tag to pull"
    required: true
  PRODUCT_LIFETIME:
    description: "Number of days to keep output files before deleting them"
    required: true
  VPC_ID:
    description: "Default VPC ID"
    required: true
  SUBNET_IDS:
    description: "Comma separated list of Subnet IDs"
    required: true
  EDL_USERNAME:
    description: "EarthData Login name to use when downloading data from ASF"
    required: true
  EDL_PASSWORD:
    description: "EarthData Login password to use when downloading data from ASF"
    required: true
  CLOUDFORMATION_ROLE_ARN:
    description: "The CloudFormation role to use for this deployment"
    required: true
  MONTHLY_JOB_QUOTA_PER_USER:
    description: "The default number of jobs any user with an Earthdata Login can run per month"
    required: true
  JOB_FILES:
    description: "Space seperated list of job spec YAMLs to include"
    required: true
  BANNED_CIDR_BLOCKS:
    description: "Comma separated list of IP CIDR blocks that will receive HTTP 403 FORBIDDEN responses from the API"
    required: true
  DEFAULT_MAX_VCPUS:
    description: "Default maximum size for the AWS Batch compute environment"
    required: true
  EXPANDED_MAX_VCPUS:
    description: "Expanded maximum size for the AWS Batch compute environment to use when month-to-date budget sufficiently exceeds month-to-date spending"
    required: true
  MONTHLY_COMPUTE_BUDGET:
    description: "Total budget allocated for AWS Batch processing per month, in dollars. Ignored when DefaultMaxvCpus = ExpandedMaxvCpus."
    required: true
  REQUIRED_SURPLUS:
    description: "Amount by which month-to-date budget must exceed month-to-date spending to increase fleet size, in dollars. Ignored when DefaultMaxvCpus = ExpandedMaxvCpus."
    required: true
  PERMISSIONS_BOUNDARY_ARN:
    description: "Arn of permissions boundary to provide to any created IAM roles"
    required: true
  SECURITY_ENVIRONMENT:
    description: "Modify resources/configurations for ASF (default), EDC, or JPL security environments"
    required: true
  AMI_ID:
    description: "Name of the Systems Manager parameter from which to retrieve the current Ami Id"
    required: true

runs:
  using: "composite"
  steps:
      - name: install dependencies and render templates
        shell: bash
        run: |
          pip install --upgrade pip
          make install
          make files='${{ inputs.JOB_FILES }}' security_environment='${{ inputs.SECURITY_ENVIRONMENT }}' build
      - name: Package and deploy
        shell: bash
        run: |
          [ -z ${{ inputs.CLOUDFORMATION_ROLE_ARN }} ] && export ROLE_STATEMENT="" \
            || export ROLE_STATEMENT="--role-arn ${{ inputs.CLOUDFORMATION_ROLE_ARN }}"

          aws cloudformation package \
            --template-file apps/main-cf.yml \
            --s3-bucket ${{ inputs.TEMPLATE_BUCKET }} \
            --output-template-file packaged.yml
          aws cloudformation deploy \
            --stack-name ${{ inputs.STACK_NAME }} \
            --template-file packaged.yml \
            $ROLE_STATEMENT \
            --capabilities CAPABILITY_IAM \
            --parameter-overrides \
                VpcId='${{ inputs.VPC_ID }}' \
                SubnetIds='${{ inputs.SUBNET_IDS }}' \
                EDLUsername='${{ inputs.EDL_USERNAME }}' \
                EDLPassword='${{ inputs.EDL_PASSWORD }}' \
                ImageTag='${{ inputs.IMAGE_TAG }}' \
                ProductLifetimeInDays='${{ inputs.PRODUCT_LIFETIME }}' \
                DomainName='${{ inputs.DOMAIN_NAME }}' \
                CertificateArn='${{ inputs.CERTIFICATE_ARN }}' \
                MonthlyJobQuotaPerUser='${{ inputs.MONTHLY_JOB_QUOTA_PER_USER }}' \
                BannedCidrBlocks='${{ inputs.BANNED_CIDR_BLOCKS }}' \
                DefaultMaxvCpus='${{ inputs.DEFAULT_MAX_VCPUS }}' \
                ExpandedMaxvCpus='${{ inputs.EXPANDED_MAX_VCPUS }}' \
                MonthlyComputeBudget='${{ inputs.MONTHLY_COMPUTE_BUDGET }}' \
                RequiredSurplus='${{ inputs.REQUIRED_SURPLUS }}' \
                PermissionsBoundaryPolicyArn='${{ inputs.PERMISSIONS_BOUNDARY_ARN }}' \
                AmiId='${{ inputs.AMI_ID }}'
