AWSTemplateFormatVersion: 2010-09-09

Parameters:

  VpcId:
    Type: AWS::EC2::VPC::Id

  Subnets:
    Type: List<AWS::EC2::Subnet::Id>

  EDLUsername:
    Type: String

  EDLPassword:
    Type: String
    NoEcho: true
  
  SpotFleetServiceRoleArn:
    Type: String

Resources:

  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Ref AWS::StackName
      GroupDescription: !Sub "Security group for ${AWS::StackName} machines"
      VpcId: !Ref VpcId

  ComputeEnvironment:
    Type: AWS::Batch::ComputeEnvironment
    Properties:
      Type: MANAGED
      ServiceRole: !GetAtt BatchServiceRole.Arn
      ComputeEnvironmentName: !Ref AWS::StackName
      ComputeResources:
        Type: SPOT
        SpotIamFleetRole: !Ref SpotFleetServiceRoleArn
        BidPercentage: 100
        MinvCpus: 0
        MaxvCpus: 40
        InstanceTypes:
        - r5d.xlarge
        InstanceRole: !Ref InstanceRole
        SecurityGroupIds:
        - !Ref SecurityGroup
        Subnets: !Ref Subnets
        Tags:
          Name: !Ref AWS::StackName

  JobQueue:
    Type: AWS::Batch::JobQueue
    Properties:
      JobQueueName: !Ref AWS::StackName
      Priority: 1
      ComputeEnvironmentOrder:
      - ComputeEnvironment: !Ref ComputeEnvironment
        Order: 1

  JobDefinition:
    Type: AWS::Batch::JobDefinition
    Properties:
      JobDefinitionName: !Ref AWS::StackName
      Type: container
      Parameters:
        granule: ""
        bucket: !Ref Bucket
        username: !Ref EDLUsername
        password: !Ref EDLPassword
      ContainerProperties:
        Image: hello-world
        Vcpus: 4
        Memory: 10000
        JobRoleArn: !GetAtt TaskRole.Arn
        Command:
        - --granule
        - Ref::granule
        - --username
        - Ref::username
        - --http-password
        - Ref::password
      RetryStrategy:
        Attempts: 2

  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref AWS::StackName
  
  TaskRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${AWS::StackName}-task-role"
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          Action: sts:AssumeRole
          Principal:
            Service: batch.amazonaws.com
          Effect: Allow
      Policies:
      - PolicyName: policy
        PolicyDocument:
          Version: 2012-10-17
          Statement:
          - Effect: Allow
            Action: s3:PutObject
            Resource: !Sub "arn:aws:s3:::${Bucket}/*"

  BatchServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${AWS::StackName}-batch-service-role"
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          Action: sts:AssumeRole
          Principal:
            Service: batch.amazonaws.com
          Effect: Allow
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AWSBatchServiceRole

  InstanceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${AWS::StackName}-instance-role"
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          Action: sts:AssumeRole
          Principal:
            Service: ecs.amazonaws.com
          Effect: Allow
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AmazonEC2ContainerServiceforEC2Role
