AWSTemplateFormatVersion: 2010-09-09

Parameters:

  VpcId:
    Type: AWS::EC2::VPC::Id

  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>

  EDLUsername:
    Description: Earthdata Login username to use when downloading input products.
    Type: String

  EDLPassword:
    Description: Earthdata Login password to use when downloading input products.
    Type: String
    NoEcho: true

  ImageTag:
    Type: String
    Default: latest

  ProductLifetimeInDays:
    Description: Number of days to keep output files before deleting them.
    Type: Number
    MinValue: 1
    Default: 14

  AuthPublicKey:
    Description: Public key for jwt auth provider, if using https://auth.asf.alaska.edu then keep default.
    Type: String
    Default: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDBU3T16Db/88XQ2MTHgm9uFALjSJAMSejmVL+tO0ILzHw2OosKlVb38urmIGQ+xMPXTs1AQQYpJ/CdO7TaJ51pv4iz+zF0DYeUhPczsBEQYisLMZUwedPm9QLoKu8dkt4EzMiatQimBmzDvxxRkAIDehYh468phR6zPqIDizbgAjD4qgTd+oSA9mDPBZ/oG1sVc7TcoP93FbO9u1frzhjf0LS1H7YReVP4XsUTpCN0FsxDAMfLpOYZylChkFQeay7n9CIK8em4W4JL/T0PC218jXpF7W2p92rfAQztiWlFJc66tt45SXAVtD1rMEdWGlzze4acjMn4P7mugHHb17igtlF82H/wpdm84qTPShvBp/F4YZejgAzOAxzKVbCQ8lrApk1XYVDRAVk3AphfvNK5IC/X9zDSXstH9U94z8BTjkL2fR4eKzFu5kkvVoGHAACIv72QvH06Vwd0PNzLyaNXr9D5jO61EbR4RfpbzvAG0IzgXsUq0Rj7qwvzTCu6yLwTi/fn9bmRaOQNPtBch4ai5w7cfUWe2r7ZPv31AXPm1A+aGXvYTEZkiQMrBN/dXlNdUmafNNDoMBm/frQhMl+2DZp+C9GXCr2Z/JmYUHO8PaEj6UyYTkkrmtZNlZ43Nd2TblPEzL0pprJM9MxEf2Peaai8GKmTJz6C5tSGU+XdZQ== root@9dce6b43747e

  AuthAlgorithm:
    Description: Algorithm for jwt auth provider, if using https://auth.asf.alaska.edu then keep default.
    Type: String
    Default: RS256

  DomainName:
    Description: DNS domain name that will be used to invoke this api.
    Type: String

  CertificateArn:
    Description: ARN of Certificate in AWS Certificate Manager setup previously for this domain name.
    Type: String

  MonthlyJobQuotaPerUser:
    Description: Number of jobs each user is allowed per month.
    Type: Number
    MinValue: 0

  SystemAvailable:
    Description: Set to false to shutdown system, API will run and provide errors to users, but will not accept jobs.
    Type: String
    Default: true
    AllowedValues:
      - false
      - true

Outputs:

  ApiUrl:
    Value: !GetAtt Api.Outputs.Url

Resources:

  Api:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        JobsTable: !Ref JobsTable
        AuthPublicKey: !Ref AuthPublicKey
        AuthAlgorithm: !Ref AuthAlgorithm
        DomainName: !Ref DomainName
        CertificateArn: !Ref CertificateArn
        MonthlyJobQuotaPerUser: !Ref MonthlyJobQuotaPerUser
        SystemAvailable: !Ref SystemAvailable
      TemplateURL: api/api-cf.yml

  Cluster:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        VpcId: !Ref VpcId
        SubnetIds: !Join [',', !Ref SubnetIds]
        ContentBucket: !Ref ContentBucket
      TemplateURL: compute-cf.yml

  StepFunction:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        JobQueueArn: !GetAtt Cluster.Outputs.JobQueueArn
        TaskRoleArn: !GetAtt Cluster.Outputs.TaskRoleArn
        JobsTable: !Ref JobsTable
        EDLUsername: !Ref EDLUsername
        EDLPassword: !Ref EDLPassword
        Bucket: !Ref ContentBucket
        ImageTag: !Ref ImageTag
      TemplateURL: workflow-cf.yml

  Monitoring:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        StepFunctionArn: !GetAtt StepFunction.Outputs.StepFunctionArn
        ApiId: !GetAtt Api.Outputs.ApiId
      TemplateURL: monitoring-cf.yml

  LogBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: LogDeliveryWrite
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True
        IgnorePublicAcls: True
        BlockPublicPolicy: True
        RestrictPublicBuckets: True

  ContentBucket:
    Type: AWS::S3::Bucket
    Properties:
      LoggingConfiguration:
        DestinationBucketName: !Ref LogBucket
        LogFilePrefix: s3-access-logs/content-bucket/
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True
        IgnorePublicAcls: True
        BlockPublicPolicy: False
        RestrictPublicBuckets: False
      LifecycleConfiguration:
        Rules:
          - Status: Enabled
            TagFilters:
              - Key: file_type
                Value: product
            ExpirationInDays: !Ref ProductLifetimeInDays
          - Status: Enabled
            AbortIncompleteMultipartUpload:
              DaysAfterInitiation: 1

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref ContentBucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal: "*"
            Action: s3:GetObject
            Resource: !Sub "${ContentBucket.Arn}/*"

  JobsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: job_id
          AttributeType: S
        - AttributeName: user_id
          AttributeType: S
        - AttributeName: status_code
          AttributeType: S
        - AttributeName: request_time
          AttributeType: S
      KeySchema:
        - AttributeName: job_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: user_id
          KeySchema:
            - AttributeName: user_id
              KeyType: HASH
            - AttributeName: request_time
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: status_code
          KeySchema:
            - AttributeName: status_code
              KeyType: HASH
          Projection:
            ProjectionType: ALL
