AWSTemplateFormatVersion: 2010-09-09

Parameters:

  ComputeEnvironmentArn:
    Type: String

  DefaultMaxvCpus:
    Type: Number
    MinValue: 0

  ExpandedMaxvCpus:
    Type: Number
    MinValue: 0

  MonthlyComputeBudget:
    Type: Number
    MinValue: 0

  RequiredSurplus:
    Type: Number
    MinValue: 0

  PermissionsBoundaryPolicyArn:
    Type: String

  SecurityGroupId:
    Type: String

  SubnetIds:
    Type: CommaDelimitedList

Conditions:

  UsePermissionsBoundary: !Not [!Equals [!Ref PermissionsBoundaryPolicyArn, ""]]

  LambdasInVpc: !Not [!Equals [!Ref SecurityGroupId, ""]]

Resources:

  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${Lambda}"
      RetentionInDays: 90

  Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          Action: sts:AssumeRole
          Principal:
            Service: lambda.amazonaws.com
          Effect: Allow
      PermissionsBoundary: !If [UsePermissionsBoundary, !Ref PermissionsBoundaryPolicyArn, !Ref AWS::NoValue]
      ManagedPolicyArns:
        - !Ref TaskPolicy

  TaskPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - logs:CreateLogStream
              - logs:PutLogEvents
            Resource: !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/*"
          - Effect: Allow
            Action:
              - ce:GetCostAndUsage
              - batch:DescribeComputeEnvironments
            Resource: "*"
          - Effect: Allow
            Action: batch:UpdateComputeEnvironment
            Resource: !Ref ComputeEnvironmentArn

  Lambda:
    Type: AWS::Lambda::Function
    Properties:
      Environment:
        Variables:
          COMPUTE_ENVIRONMENT_ARN: !Ref ComputeEnvironmentArn
          MONTHLY_COMPUTE_BUDGET: !Ref MonthlyComputeBudget
          DEFAULT_MAX_VCPUS: !Ref DefaultMaxvCpus
          EXPANDED_MAX_VCPUS: !Ref ExpandedMaxvCpus
          REQUIRED_SURPLUS: !Ref RequiredSurplus
      Code: src/
      Handler: scale_cluster.lambda_handler
      MemorySize: 128
      Role: !GetAtt Role.Arn
      Runtime: python3.8
      Timeout: 30
      VpcConfig:
        !If
          - LambdasInVpc
          - SecurityGroupIds:
              - !Ref SecurityGroupId
            SubnetIds: !Ref SubnetIds
          - !Ref AWS::NoValue

  EventInvokeConfig:
    Type: AWS::Lambda::EventInvokeConfig
    Properties:
      FunctionName: !Ref Lambda
      Qualifier: $LATEST
      MaximumRetryAttempts: 0

  Schedule:
    Type: AWS::Events::Rule
    Properties:
      ScheduleExpression: "rate(6 hours)"
      Targets:
        - Arn: !GetAtt Lambda.Arn
          Id: lambda

  EventPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt Lambda.Arn
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt Schedule.Arn
