name: Deploy Environments

on:
    workflow_dispatch: {}


jobs:
  setup-matrix:
    runs-on: ubuntu-latest
    outputs:
      deploy-matrix: ${{ steps.setup-deploy.outputs.deploy-config-files }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup cdk-deploy Matrix
        id: setup-deploy
        run: |
          github_vars_list=$(echo "${{ vars.DEPLOY_ENVIRONMENTS }}" | tr '\r\n' ' ')
          json_list=$(echo $github_vars_list | jq --raw-input --compact-output 'split(" ")')
          echo "deploy-config-files=$json_list" >> "$GITHUB_OUTPUT"
          if [ $json_list == '[]' ]; then
              echo "> [!WARNING]" >> $GITHUB_STEP_SUMMARY
              echo "> **No deploy examples found**, skipping deployments. Populate the 'DEPLOY_ENVIRONMENTS' GH Variable to change." >> $GITHUB_STEP_SUMMARY
          fi

  hyp3-deploy:
    runs-on: ubuntu-latest
    needs:
      - setup-matrix
    strategy:
      # Since they all use the Base Stack, only one can create/update at a time:
      max-parallel: 1
      matrix:
        deploy-config: ${{ fromJson(needs.setup-matrix.outputs.deploy-matrix) }}
    environment:
      name: "${{ matrix.deploy-config }}"
      url: https://${{ vars.domain }}
    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.V2_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.V2_AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.V2_AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - run: |
          jq -n '{"Parameters": $ARGS.named}' \
            --arg VpcId '${{ secrets.VPC_ID }}' \
            --arg SubnetIds '${{ secrets.SUBNET_IDS }}' \
            --arg SecretArn '${{ secrets.SECRET_ARN }}' \
            --arg ImageTag '${{ vars.IMAGE_TAG }}' \
            --arg ProductLifetimeInDays '${{ vars.product_lifetime_in_days }} ' \
            --arg AuthPublicKey '${{ secrets.AUTH_PUBLIC_KEY }}' \
            --arg DefaultCreditsPerUser '${{ vars.default_credits_per_user }}' \
            --arg DefaultApplicationStatus '${{ vars.default_application_status }}' \
            --arg AmiId '${{ vars.ami_id }}' \
            --arg DefaultMaxvCpus '${{ vars.default_max_vcpus }}' \
            --arg ExpandedMaxvCpus '${{ vars.expanded_max_vcpus }}' \
            --arg MonthlyBudget '${{ secrets.MONTHLY_BUDGET }}' \
            --arg RequiredSurplus '${{ vars.required_surplus }}' \
            --arg InstanceTypes '${{ vars.instance_types }}' \
            --arg Domain '${{ vars.domain }}' \
            --arg CertificateArn '${{ secrets.CERTIFICATE_ARN }}' \
            > parameters.json

      - uses: ./.github/actions/deploy-hyp3
        with:
          TEMPLATE_BUCKET:  ${{ vars.template_bucket }}
          STACK_NAME: "${{ matrix.deploy-config }}"
          API_NAME: "${{ matrix.deploy-config }}"
          CLOUDFORMATION_ROLE_ARN: ${{ secrets.CLOUDFORMATION_ROLE_ARN }}
          COST_PROFILE: ${{ vars.cost_profile }}
          JOB_FILES: ${{ vars.job_files }}
          SECURITY_ENVIRONMENT: ${{ vars.security_environment }}
          PARAMETER_FILE: parameters.json
