name: Tag version

on:
  push:
    branches:
      - main

jobs:
  call-bump-version-workflow:
    uses: ASFHyP3/actions/.github/workflows/reusable-bump-version.yml@v0.17.1
    secrets:
      USER_TOKEN: ${{ secrets.TOOLS_BOT_PAK }}
