name: Test static analysis workflow

on: push


jobs:
  call-ruff-workflow:
    # Docs: https://github.com/ASFHyP3/actions
    uses: ASFHyP3/actions/.github/workflows/reusable-ruff.yml@github-actions-perms
